/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumBusinessAccountingType } from "./EnumBusinessAccountingType";
import {
  IsEnum,
  IsOptional,
  IsBoolean,
  ValidateNested,
  IsDate,
  IsString,
  IsInt,
} from "class-validator";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { EnumBusinessBusinessType } from "./EnumBusinessBusinessType";
import { Client } from "../../client/base/Client";
import { Type } from "class-transformer";

@ObjectType()
class Business {
  @ApiProperty({
    required: false,
    enum: EnumBusinessAccountingType,
  })
  @IsEnum(EnumBusinessAccountingType)
  @IsOptional()
  @Field(() => EnumBusinessAccountingType, {
    nullable: true,
  })
  accountingType?: "Unknown" | "Cash" | "Accumulated" | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active!: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  address!: JsonValue;

  @ApiProperty({
    required: false,
    enum: EnumBusinessBusinessType,
  })
  @IsEnum(EnumBusinessBusinessType)
  @IsOptional()
  @Field(() => EnumBusinessBusinessType, {
    nullable: true,
  })
  businessType?: "OsekMurshe" | "LtdCompany" | "OsekPatur" | null;

  @ApiProperty({
    required: false,
    type: () => [Client],
  })
  @ValidateNested()
  @Type(() => Client)
  @IsOptional()
  clients?: Array<Client>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  deductionId!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  deductionRate!: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  exemption!: boolean | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  taxId!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Business as Business };
